### ISSUE TITLE
Code to handle Callbacks

### ISSUE THREAD

**Issue by ooglek** [Bandwidth/php-bandwidth-iris#72]
Callbacks are awesome. 

Any chance of adding code to this library that would handle Bandwidth Callbacks -- Events, Orders, Portouts?

It would be handy to pass the incoming request to the SDK that would read and validate it and turn it into an object within the SDK with handy accessors and methods.

**Comment by ajrice6713** [comment]
Hey Peter,

Hope you are well! We are currently working to clean up our OpenAPI spec for the number management (IRIS) API - which _should_ include models for those different callbacks. 

Once the API Spec is cleaned and passes our validation - we will generate a new SDK from the spec, deprecate the current php-bandwidth-iris package, and have a new SDK that is auto-generated from the API spec as opposed to a hand written package. 

Unfortunately, because the new SDK is top of our priority list at this time, I don't see callback objects being added to the current suite of SDK's unless we run into major setbacks and are forced to support these for a longer period of time.

**Comment by ajrice6713** [comment]
Hey Peter,

Going to close this one out - we most likely wont be adding callback objects to this SDK. As we pivot our SDK strategy however, callback objects will be included in the next iteration.
