### ISSUE TITLE
Check TNs Portability

### ISSUE THREAD

**Issue by nlvedwinencomienda** [Bandwidth/php-bandwidth-iris#75]
gives me 403 response even using the `https://test.dashboard.bandwidth.com/api/`

**Comment by ajrice6713** [comment]
Hey there @nlvedwinencomienda  - the 403 is generally a permissions issue with your user

An important note - dashboard and test.dashboard are entirely seperate environments - meaning credentials are not shared across the two 

What you most likely need to do is log in to [dashboard.bandwidth.com](dashboard.bandwidth.com) and set the correct role on your user to be able to access the endpoint you are requesting (i.e. the ordering role needs to be turned on for ordering tns, line feature management needs to be turned on to manage line features (tnOptions orders), etc) 

If you have trouble with that you may be better suited opening a support ticket at [support.bandwidth.com](support.bandwidth.com)

**Comment by ajrice6713** [comment]
@nlvedwinencomienda i just saw that the issue was opened for the portability checker endpoint - your user needs the `porting` role to access the functionality within our API

**Comment by ajrice6713** [comment]
Hey @nlvedwinencomienda 

Going to close out this issue - however if updating the role on your end doesn't seem to resolve the issue, please feel free to open a support ticket and we can go ahead and check out your user roles on our side to see whats going on - at this time i believe the issue is related to overall permissions and not an SDK bug, so a support ticket would be the proper channel to resolution for this if you are still stuck. 

Thanks!
